# Smaccer Configuration

# Do not change this (Only for internal use)!
config-version: 1.2

# Enable or disable the auto update checker notifier.
update_notifier: true

# World Query Message Formats
# Customize how world information is displayed in the nametag.

# When all specified worlds are loaded.
# Placeholders:
#   - {world_names}: Comma-separated list of loaded world names.
#   - {count}: Total player count across loaded worlds.
world_message_format: "§aWorlds: §b{world_names} §a| Players: §e{count}"

# When some or all specified worlds are not loaded.
# Placeholders:
#   - {world_names}: Comma-separated list of loaded world names.
#   - {not_loaded_worlds}: Comma-separated list of worlds not loaded.
#   - {count}: Total player count across loaded worlds.
world_not_loaded_format: "§cWorlds: §b{world_names} §c| Not Loaded: §7{not_loaded_worlds} §c| Players: §e{count}"

# Server Query Message Formats
# Customize how server information is displayed in the nametag.

# When the server is online.
# Placeholders:
#   - {online}: Current number of players online.
#   - {max_online}: Maximum number of players allowed online.
server_online_format: "§aServer: §b{online}§a/§b{max_online} §aonline"

# When the server is offline.
server_offline_format: "§cServer: Offline"

# Default settings for NPCs.
npc-default-settings:
  # Cooldown settings for NPC commands.
  # - enabled: Whether command cooldown is enabled or not.
  # - value: Cooldown duration in seconds.
  commandCooldown:
    enabled: true
    value: 3

  # Rotation settings for NPC behavior.
  # - enabled: Whether rotation is enabled or not.
  # - maxDistance: Maximum distance for NPC rotation.
  rotation:
    enabled: true
    maxDistance: 8

  # Nametag visibility settings for NPCs.
  # - enabled: Whether nametag visibility is enabled or not.
  nametagVisible:
    enabled: true

  # Default entity visibility settings.
  # - value: Integer representing visibility level.
  #     0: Visible to everyone.
  #     1: Visible only to the creator.
  #     2: Invisible to everyone.
  entityVisibility:
    value: 0

  # Slap settings for NPCs.
  # - enabled: Whether slap-back action is enabled or not.
  # Note: Set to true if slap action is intended for human NPCs.
  slapBack:
    enabled: true

  # Cooldown settings for NPC emotes.
  # - enabled: Whether emote cooldown is enabled or not.
  # - value: Cooldown duration in seconds.
  # Note: Emotes are non-interactive gestures or expressions performed by NPCs.
  emoteCooldown:
    enabled: true
    value: 5

  # Cooldown settings for NPC action emotes.
  # - enabled: Whether action emote cooldown is enabled or not.
  # - value: Cooldown duration in seconds.
  # Note: Action emotes are interactive gestures or expressions that trigger specific actions when performed by NPCs.
  actionEmoteCooldown:
    enabled: true
    value: 5

  # Gravity settings for NPCs.
  # - enabled: Whether gravity is enabled or not.
  gravity:
    enabled: true
